# SS 2021 SEMINAR 05 Reinforcement Learning in der Sprachtechnologie
## Reinforcement Learning II 

## A) Discussion


**Interesting papers I stumbled upon recently:**

* Planning to Explore with Self-Supervised Models: https://www.semanticscholar.org/paper/Planning-to-Explore-via-Self-Supervised-World-Sekar-Rybkin/3a71c306eb6232658c9e5fd48aed1ef3befe5fbe

* World Models: https://www.semanticscholar.org/paper/World-Models-Ha-Schmidhuber/ff332c21562c87cab5891d495b7d0956f2d9228b

**RL Applications that could be interesting for you:**

* Robotics: Solving Rubik's Cube: https://www.youtube.com/watch?v=x4O8pojMF0w

* Robotics: Do you love me?: https://www.youtube.com/watch?v=fn3KWM1kuAw

* Self-Driving-Cars: Openpilot: OPEN SOURCE SELF-DRIVING CARS(!!!) https://www.youtube.com/watch?v=YJzvrDBQwOE, https://github.com/commaai/openpilot

* Dota 2: OpenAI5 https://www.youtube.com/watch?v=UZHTNBMAfAA

**Practical RL Tutorials** 

* OpenAI Gym + Keras: https://www.youtube.com/watch?v=hCeJeq8U0lo
 

**Presentations** 

* Please find our dates in our repository: https://github.com/clause-bielefeld/SS_2021_SEMINAR_Reinforcement_Learning_in_der_Sprachtechnologie/blob/main/README.md

**REMEMBER: HOMEWORK SUBMISSION DEADLINE: May 19th, MAIL: henrik.voigt@uni-jena.de, NAMING: HOMEWORK_01_FIRSTNAME_LASTNAME.ipynb**

***

## B) Theory

### REINFORCEMENT LEARNING II

#### RL in Detail


**Reinforcement Learning is creating a POLICY function that enables an agent to reach a certain GOAL in an optimal way, by using sparse positiv/negative feedback.**

**Deep Reinforcement Learning is the application of DEEP LEARNING methods to learn the POLICY function.**

<br>

**LET'S DRAW WHAT WE KNOW SO FAR**: 

<img src="https://www.wikihow.com/images/0/08/Draw-a-Map-of-an-Imaginary-Place-Step-12.jpg" width="500"/>

<br>

What do Reinforcement Learning Agents learn? 

Optimal Policies!

**GOALS** 

Goals can be formulated in terms of **RETURN**. This makes it very handy because BIG goals can be **deconstructed** into smaller sub-goals, which  are states of the world that give some reward and when solved together the expected return is maximized (and the overall goal is solved). 

Therefore we define a goal, which can be decomposed into smaller subgoals and for each of those subgoals we get a positive reward. To reach the overall goal in an **OPTIMAL** way, the expected return has to be maximized. 

<img src="https://dsmedia.ign.com/ds/image/article/122/1223480/new-super-mario-bros-2-20120420085937760-001.jpg" width="500"/>
    
<br>    
<br>     

**POLICIES** 

A policy in a simple way is just a function that takes in a state and puts out an action.

Policies are "super-plans". A policy is like having the optimal plan, but from  **EVERY STATE** of the world, no matter which. That means, no matter where we start, we know the optimal action that maximizes the expected return. Always. 

Under the hood a policy is a probability distribution over actions, where the probability of taking action a in state s is PI(a|s). 
        
Optimal Policy: 

The **OPTIMAL POLICY** is the policy, that yields more return to the agent than all other policies. A policy is better than another policy if the **VALUE** of it (=expected return in every state) is greater or equal than the return of another policy in ALL states. 

The optimal policy has an associated optimal *state-value function*. The optimal policy has an associated optimal *action-value function*. 
    
<img src="https://miro.medium.com/max/386/1*dpJKumwuULjYKLaHjTxr7g.png" width="500"/>

<br>    
<br>   

**VALUE FUNCTIONS** 

Value functions are functions of states or state-action pairs. A value function in general estimates how good a certain **STATE** or a certain **ACTION** (EVALUATION of states and actions => estimate how good it is to be in a state concerning the reaching of a goal or how good it is to take a certain action in a state concerning a goal).

Value functions are always directly connected to/dependend to a policy!! That means, that having a policy, we can compute the VALUE of each state respected to that policy. 

How do we derive the VALUE of a state?  

We define the value of a state as the **expected, discounted reward** by entering the state and following policy pi towards the goal afterwards. This can be seen as a projection of the future return into the respective state. 

But how do we derive this then for all states?

By using the **BELLMAN EQUATION**.
    
The *BELLMAN EQUATION* allows us to derive the VALUE of a STATE. It also shows us that the value can be **decomposed** into the **IMMEDIATE REWARD** in that state and the **DISCOUNTED REWARD** of all future states towards the goal following a policy PI. 

<br>    
<br>  

<img src="https://miro.medium.com/max/379/1*RIMbwQAUJymRMgo5gMJZVg.png" width="500"/>

<br>    
<br>  

**BELLMAN UPDATE**

The Bellman Update tells us how to update our values after each iteration: 

<img src="https://miro.medium.com/max/537/1*W1tVhkVa9obVCvA3PTJ_gw.png" width="500"/>

That means, that the **Optimal Value Function** is recursively related to the Bellman Optimality Equation. 

STATE-VALUE-FUNCTION:

State value functions evaluate each state with respect to its **RETURN** following a policy PI. Which states are the most valueable states? which state from my current one is the most valuable next one? 

State value function gives us the value of a state S under a policy PI, that means how good is it to be in that state concerning the maximization of our expected return. 
    
<img src="https://miro.medium.com/max/700/1*7Kjo-ibNy_jDX2hvnLnROA.png" width="600"/>

<br>    
<br>    
<br>    
<br>    
    
ACTION-VALUE-FUNCTION:

The action-value function is evaluating each **state-action pair** with respect to its **RETURN** following policy PI. Which action is the most valuable one in the current state?

The action value function tells us how good it is to take any of the possible actions a in a given state following policy pi. This means it gives us the value of an action in a specific state under policy pi. 

The value of an action in a certain state is called the Q value. The action value function is sometimes also called Q Function (technically this is depending on the knowledge of a TRANSITION function ...).  

The optimal q-function must satisfy the BELLMANN OPTIMALITY EQUATION, which is used to update it. 

<img src="https://miro.medium.com/max/700/1*4Fdbohxs6LedqarJjw65Qg.png" width="500"/>

<br>    
       
    
***


### Reinforcement Learning Algorithms    

#### Model Based Reinforcement Learning
    
The idea in model-based-RL is that we can solve a markov decision problem programmatically when having the **STATE TRANSITION FUNCTION** and the **REWARD FUNCTION** completely through computation. 

<img src="https://www.researchgate.net/profile/Jie-Fu-24/publication/274094617/figure/fig1/AS:614238733217807@1523457334832/Example-of-an-MDP-with-states-Q-s-i-i-0-7-actions-A-a-b-and.png" width="500"/>

The base for this computation are the **BELLMAN EQUATIONS**, which prove, that a markov decision process can be solved when having the STATE TRANSITION FUNCTION and the REWARD FUNCTION by computing an OPTIMAL STATE VALUE FUNCTION. 

Two methods for solving this are either VALUE ITERATION or POLICY ITERATION. To iteratively build the value function or the policy in each step a BELLMAN UPDATE / BACKUP is performed
    
Methods applied in this field are *dynamic programming*(DIVIDE & CONQUER) or *monte-carlo-methods*(INTELLIGENT SAMPLING). This method implies the extraction of important **concepts** of the environment (e.g. opponents, positions, states) and the **transitions** (= mechanics/physics of the environment, e.g. is it turn-based, how to move, act, ...). 
     
#### Value Iteration
    
= Iterating the State-Value Function using Bellman Update Rules (top down). Model based approach, because we know the transition probabilities and rewards. In Q Learning the agent does also a form of value iteration, but it does not know state transition probabilities. 
<br> 
<br>
#### Policy Iteration

= Iterating the Policy (function that maps states to actions). For each policy we derive, we compute the value function. Then we evaluate the value function the policy creates (policy evaluation) and improveme our policy using the bellman update (bottom up).
<br>    
<br>
#### PLANNING | SEARCHING | DYNAMIC PROGRAMMING | MONTE CARLO METHODS | WORLD METHODS
    
Planning is an adaptive way of model based reinforcement learning, which is based because of the HIGH COMPUTATIONAL EFFORT that value iteration and policy iteration deliver. 

In value iteration and policy iteration the TRANSITION FUNCTION and the REWARD FUNCTION are fully known.

It becomes easy to see, that in more complex set ups with bigger state and action spaces this becomes not computationally feasable to solve for an agent. 

One method to solve this is to use PLANNING, which is deriving an OPTIMAL PATH from the current state to the GOAL STATE, or, if the state space is too vast (as e.g. in chess, dota, ...) to derive an N-STEP LOOK-AHEAD towards the goal state. 
<br>
<br>
#### Model-Free Reinforcement Learning
    
The idea in model-free RL is to learn how to act optimally based on past **experience**/interactions with the environment and derive an optimal policy from that without building a model of the world, which is basically NOT KNOWING A TRANSITION FUNCTION and NOT KNOWING THE REWARD FUNCTION (INTUITION).  

For updating our action-value function we use a derivative of the bellman update for Q-Functions. A Q-Function is basically the same as a action-value function WITHOUT having a TRANSITON FUNCTION. 
<br>
<br>
#### Q-Learning

Q-Learning is an approach of solving an MDP by LEARNING the optimal q-values. A Q-VALUE is the value of an ACTION in a certain STATE. Q Learning is model free approach. 

That means, a Q-VALUE describes how VALUABLE it is to execute an ACTION concerning the **expected, discounted reward**, by following the current policy PI. 

The Q-Learning algorithm updates the q-values of each state action pair using the bellman optimality equation and the bellman update rules. 
    
Exploration Exploitation dilemma approach here: when choosing an action, we can introduce a factor epsilon here, that randomly decides to explore or exploit, which implements how we face this dilemma. 

***


## C) Practice

#### Reinforcement Learning II

Today: Implementing our first bot!

I am using the gym environment of openai today. 
You can install it this way: 

`conda install -c conda-forge gym`

The game we try to solve is the frozen lake game:
<img src="https://camo.githubusercontent.com/f558f268f3c1a45f0a88342113476f34ce894896c30b66fdc3101c8d090a0a0a/68747470733a2f2f616e616c7974696373696e6469616d61672e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031382f30332f46726f7a656e2d4c616b652e706e67" width="500"/>

For this we use the openai gym environment implementation from here: 
https://gym.openai.com/envs/FrozenLake-v0/

You can find the source code in this repository:
https://github.com/openai/gym/blob/master/gym/envs/toy_text/frozen_lake.py

The environment is an implementation of the same interface as we implemented last week. 

Let's start:

-----

In [27]:
# Check GPU reachability 
import torch
print(torch.__version__)
print(torch.cuda.is_available())

1.7.1
True


In [28]:
import numpy as np
import gym 
import random 
import time
from IPython.display import clear_output

In [29]:
# get an instance of the frozen lake gym environment
env = gym.make("FrozenLake-v0")

In [30]:
# get some information from the environment
action_space = env.action_space
#print(action_space)
action_space_size = env.action_space.n
#print(action_space_size)
state_space = env.observation_space 
print(state_space)
state_space_size = env.observation_space.n
print(state_space_size)

Discrete(16)
16


In [31]:
# Q-TABLE
# build our action-value table | Q-TABLE
# as you already know, the q-table looks like this
# state | action_space

q_table = np.zeros((state_space_size, action_space_size))
#print(q_table)

In [32]:
# Training Parameters
num_episodes = 10000
max_steps_per_episode = 100

# q-learning | update parameters
learning_rate = 0.1
discount_rate = 0.99

# exploration-exploitation trade off
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [33]:
# Q-LEARNING

# collect rewards somewhere to visualize our learning curve
rewards_of_all_episodes = []

# Training Loop
for episode in range(num_episodes):
    # reset/initialize the environment first
    state = env.reset()
    # set done back to false at the beginning of an episode
    done = False
    # reset our rewards collector | return for the beginning episode
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        # select an action
        # use our exploration exploitation trade off -> do we explore or exploit in this timestep ?
        exploration_rate_threshold = random.uniform(0,1)
        if(exploration_rate_threshold > exploration_rate):
            action = np.argmax(q_table[state, : ])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        # Update Q-Table Q(s,a) using the bellman update  
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, : ]))
        
        # update the state to the new state
        state = new_state
        # collect the reward
        rewards_current_episode += reward
        
        if (done == True):
            break
    
    # after we finish an episode, make sure to update the exploration rate
    # decay the exploration rate the longer the time goes on
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    # append our rewards for this episode for learning curve
    rewards_of_all_episodes.append(rewards_current_episode)

In [34]:
# LEARNING STATISTICS 
# for each episode print the stats of the episode
rewards_per_thousand_episodes = np.split(np.array(rewards_of_all_episodes),num_episodes/1000)
count = 1000
print('*****INFO: average reward per thousand episodes: ***** \n')
for reward in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(reward/1000)))
    count += 1000
    
# print our learned q-table
print("\n\n ***** Q-TABLE ***** \n")
print(q_table)

*****INFO: average reward per thousand episodes: ***** 

1000 :  0.037000000000000026
2000 :  0.19900000000000015
3000 :  0.3960000000000003
4000 :  0.5760000000000004
5000 :  0.6420000000000005
6000 :  0.6700000000000005
7000 :  0.6820000000000005
8000 :  0.6660000000000005
9000 :  0.6840000000000005
10000 :  0.6730000000000005


 ***** Q-TABLE ***** 

[[0.59709926 0.45967051 0.49482058 0.49042446]
 [0.27493479 0.35435928 0.33467266 0.50606189]
 [0.38700126 0.37887474 0.37949189 0.45597048]
 [0.29731293 0.3101768  0.30679792 0.42787359]
 [0.61297439 0.35201328 0.43065625 0.38352635]
 [0.         0.         0.         0.        ]
 [0.17116911 0.17446989 0.36932612 0.13972523]
 [0.         0.         0.         0.        ]
 [0.50810251 0.40024022 0.43867213 0.64934984]
 [0.46785004 0.70719625 0.34680311 0.49487922]
 [0.61295413 0.40262048 0.37166018 0.3131942 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.54603719 0.56039832 0.7742407

In [26]:
# PURE EXPLOITATION | watching our agent play
for episode in range(3):
    state = env.reset()
    done = False
    print("INFO:*****EPISODE ", episode+1, "\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("INFO: ***** agent reached the goal. *****")
                time.sleep(3)
            else:
                print("INFO: ***** agent died.")
                time.sleep(3)
            clear_output(wait=True)
            break
        
        state = new_state

env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
INFO: ***** agent reached the goal. *****


In [36]:
# DEEP REINFORCEMENT LEARNING
# DEEP Q LEARNING

# next week

***

# TODO's

1. Send your finished presentations (+ possibly annotated paper) by **Monday 12.00 AM/midnight** via email to henrik.voigt@uni-jena.de

3. SEND your little HOMEWORK to henrik.voigt@uni-jena.de unitl **19TH OF MAY** by using the naming convention: HOMEWORK_01_FIRSTNAME_LASTNAME.ipynb until May 19th 00.00 AM/midnight

***
