# SS 2021 SEMINAR 07 Reinforcement Learning in der Sprachtechnologie
## Practice Session II : RL Examples in Python

### Announcements

#### Papers

* Awesome work!

* Last time we spoke about language aquisitoin and the role of RL in that: What Topics are you interested in related to RL and NLP? Let me know, so we can discuss!

#### Homework
        
* DEADLINE: JUNE 19th

#### Future

* We are moving towards the practical sessions, that means we will have paper discussions, a very rough topic discussion (5-10 min) and then we will take a look at CODE

***

### A) Paper Presentation I: Daniel

### Title: Sentiment Analysis for Reinforcement Learning

#### Link:
[Sentiment Analysis for Reinforcement Learning](https://arxiv.org/abs/2010.02316v1)

#### Summary:

That paper shows the advantage of sentiment analysis in sparse reward enviorments, especially in Text based games.
Instead of training straight forward to reach the sparse goal states, the seniment of the enviormental feedback is analyzed, and decisions are made upon this analysis. The authors first state the problem and the common aproaches, show their aproach and show the advantages of their approach in metrics.

#### Problem/Task/Question:
Can we use sentiment analysis to convert a sparse reward problem into a dense one?

For this task the following partial problems need to be addressed:
- Sentiment analysis in NLP and RL (generating auxiliary rewards)
- Actually training for solving the task


#### Solution/Idea/Model/Approach:
![alt text](https://raw.githubusercontent.com/clause-bielefeld/SS_2021_SEMINAR_Reinforcement_Learning_in_der_Sprachtechnologie/main/materials/images/Model01_Sentimentortrag.png "")

**Overall Structure:** 

Text description represents a state:
- LSTM is used to encode the state
    - LSTM receives the words as input
    - produces state repr. as avg. of all LSTM outputs
- the encoding is feeded into the DQN
    - 2 Layer NN that calculates Q-Function

enviorment:
- TextWorld learning environment for text-based games
    - centered on cooking a recipe, requiring agents to determine the necessary ingredients from a recipe book
    - collecting in the house
    - overcoming obstacles
    - changing obstacles, ingredients, recipes, and environment
- 1,048 TextWorld game trajectories (524 wins and 524 losses)

Training on auxiliary Data:
- Chat from players with game, that does not change state
- Hypothesis: this chat ist more sentiment loaded than the rest


RL with supplement reward:
- The reward, given by the enviorment is supplemented  
- This is done by a sentiment-based reward extracted from the state representation
- Even if the enviormental reward is 0, it can speed up learning
- assumption: access to positive and negative trajecories for sentiment analyzer
- experience replay
    - successfull trajectories are replayed more often
- Using a fine-tuned BERT for learning from the enviorment and the chat
- Correlation between mean positive senitment in trajectory and success (0.713)
- Banter (text from users to chat) is mostly positive if winning






**reinforcement learning spaces:**

**state:**
 - text of the last feedback + the preceeding states

**action:**
- action is to choose between different alternatives in textbased games

**reward**
- of course the main reward
- intermediate rewards
- auxilliary rewards

**transition**
- calculate sentiment and choose next action based on that


#### Results:

- The problem of to high auxilliary rewards, so no motivation is there to explore further
    - this is solved by scaling the reward down to 10%
- evalutating models in two settings: with \<Model\> and without intermediate results \<Model-Zero\>

**Different Models**
- Naive Bayes
- BERT (fine-tuned on Stanford movie review dataset, positive and negative trajectories, banter)
    - Extra Variant with threshold about polarity (pos or neg) in state, cause they are noisy

**Evaluation**
- Assumption: agent is interacting in same env. like trained
- For fair comparrison: only include rewards received by inviorment
- the authors say that the maximum score @ the end matters the most, because model migth reach optimum at the end
- Large auxiliary rewards aren't, cause migth steer agent away from goal
![alt text](https://raw.githubusercontent.com/clause-bielefeld/SS_2021_SEMINAR_Reinforcement_Learning_in_der_Sprachtechnologie/main/materials/images/TrainingResults.png "")
![alt text](https://raw.githubusercontent.com/clause-bielefeld/SS_2021_SEMINAR_Reinforcement_Learning_in_der_Sprachtechnologie/main/materials/images/TrainingResultsTable.png "")
- auxiliary rewards without intermediate reward are much noisier
- intermediate Rewards have direct access to the game
- naive Bayes is working on word-level -> no semantic meaning
- Banter-BERT oes not perform better as vanilla model (without auxilliary)
    - most likely bad generalization
- Other Berts Outperform Vanilla Models
    - BERT-Traj is best because of high domain-similarity

#### Conclusion and annotations
- auxiliary rewards can halp improve RL agents in text domains
- can maybe be used in task oriented dialogue

**Similiarities**
- The approach has similarities to intrinsically motivated RL
    - IMRL has only intrinsic rewards (observation of enviorment)
    - Sentiment engine can be considered as IMRL
- similarity to techer student Method
    - sentiment analysis is teacher that provides Feedbeck
![alt text](https://raw.githubusercontent.com/clause-bielefeld/SS_2021_SEMINAR_Reinforcement_Learning_in_der_Sprachtechnologie/main/materials/images/IMRL.png "")

#### Critical Discussion:

* **+** Very good Language
* **+** Methods are shown well




* **-** The domain in which this can be used is very Limited
* **-** The auxiliary rewards are very noisy
* **-** The models do not generalize well (as shown)

***

### A) Paper Presentation II: Harry

### Title: Data Boost: Text Data Augmentation Through Reinforcement Learning Guided Conditional Generation

### Link: 
https://arxiv.org/abs/2012.02952

### Summary:
The paper presents a framework, Data Boost, that can augment text data. It shows how data augmentation was implemented using reinforcement learning. Data Boost shows great results compared to other methods of data augmentation. Furthermore, Data Boost can benefit classifiers.

### Problem/Task/Question:
Typically, classifiers have low performance when the data is low. The idea to solve the problem is to add modified copies of the existing data for training. <br>
The challenge is to generate good data that reflects the original class labels and has as good readability as the original data. Previous methods are not convincing and suffer from poor readability, unsatisfactory semantic consistency and lexical shrinkage
 

<img src="https://raw.githubusercontent.com/clause-bielefeld/SS_2021_SEMINAR_Reinforcement_Learning_in_der_Sprachtechnologie/main/materials/images/example_augmentation.png" alt="example_augmentation" style="zoom:50%;" />


### Solution/Idea/Model/Approach:
use of **state-of-the-art language models**
+ trained normally on a **large** amount of **data**
+ **key idea**: use the resource contained in the language models
+ language models will generate the augmented data
    + use of **natural language understanding**
    + use of **natural language generation**
    <br><br>



built **off-the-shelf** language model (**vanilla GPT-2**)
+ GPT-2 is an unsupervised **large transformer-based** language model trained to generate text by predicting the next word in a sequence of tokens
    + trained on a dataset of 8 million web pages
+ **no need** for **external datasets or training** separate systems from the scratch
+ off-the-shelf GPT-2 language model with modified decoding stage without changed architecture
+ convert GPT-2 into a conditional generator 
    + **guide** the generator towards specific class labels during its decoding stage **through reinforcement learning**


<img src="https://raw.githubusercontent.com/clause-bielefeld/SS_2021_SEMINAR_Reinforcement_Learning_in_der_Sprachtechnologie/main/materials/images/LM.png" alt="LM" style="zoom:50%;" />



**Reward Function**

<img src="https://raw.githubusercontent.com/clause-bielefeld/SS_2021_SEMINAR_Reinforcement_Learning_in_der_Sprachtechnologie/main/materials/images/Reward-Function.png" alt="example_augmentation" style="zoom:65%;" />


+ **state** $s_t = x_{<t}$ 
+ **action** $a_t$ 
+ $\pi_\theta$ term is the **unconditional policy**
    - Unconditional Policy: $\pi_{\theta}(a_t|s_t)=softmax(h^{\theta}_{<t}$)

+ $\pi_{\theta_c}$ is the **conditional policy**
    + the only difference is that we are using the conditional parameter in the hidden states
    - Conditional Policy: $\pi_{\theta_c}(a_t|s_t)=softmax(h^{\theta_c}_{<t})$

+ $G(x^c_t)$ **Salience Gain** of specified class label
    + salience gain is determined by the specified class label
    + the salience gain measures how closely the generated token resembles the salient lexicon of the target label and serves as a guide signal for the conditional generation 
    + salient lexicon
        + calculate the salience score for each word of a vocabular and pick the top-N highest words as the salient lexicon $w_c$ for all class label. 
        + N is a hpyerparameter
    

+ **KL Divergence** ($KL(\theta ||\theta_c)$) tries to guarantee the conditional policy and uncontrolled policy are not too far away

+ **Policy Gradient**:  two changes to classic SGD
    + **temperatur T** to control the strength of the updates
    + **accumulate K steps** during this reinforcement learning procedure

<img src="https://raw.githubusercontent.com/clause-bielefeld/SS_2021_SEMINAR_Reinforcement_Learning_in_der_Sprachtechnologie/main/materials/images/PolicyGradient.png" alt="PolicyGradient" style="zoom:65%;" />
<br><br>


### Results/Findings: 

Evaluation on three different Tasks
+ **Irony Classification, Sentiment Analysis, Offense Detection**
+ datasets with 2, 3 and 4 classes
+ different in size


**Improvement**: 
+ **fine-tuned BERT** as the judge classifier
+ Data Boost can even **improve** the performance of large-scale language model based classifier, like BERT.
+ much improvement at extreme data scarcity cases - about **10 percent**
+ achieved absolute **F1** increase
  + **F1-score** is a measure of a test's accuracy. It is the **harmonic mean** of the **precision** and **recall**


<img src="https://raw.githubusercontent.com/clause-bielefeld/SS_2021_SEMINAR_Reinforcement_Learning_in_der_Sprachtechnologie/main/materials/images/Improvement.png" alt="Improvement" style="zoom:50%;" />
<br><br>

**Coherence** (Stimmigkeit / Zusammenhang)
+ generated Data correspondence to the original class
+ visualizing with t-SNE that is a statistical method for high-dimensional data (sentence to vector)
+ Boost manages to guide the generation towards the target labels
+ for the most part, the distribution of generated sentences matches that of the original data

<img src="https://raw.githubusercontent.com/clause-bielefeld/SS_2021_SEMINAR_Reinforcement_Learning_in_der_Sprachtechnologie/main/materials/images/Coherence.png" alt="Coherence" style="zoom:50%;" />
<br><br>

 **Robustness**
 + tested on 5 classifiers with different architectures, including state-of-the-art language models
 + helpful and efficient with different types of classifiers
 + Data Boost generally improves the performance of all the classifiers, regardless of the classifier architecture
 + also beneficial for complex LM-based classifiers, which are already trained on a large corpus and generally used as strong baselines for text classification tasks
 

<img src="https://raw.githubusercontent.com/clause-bielefeld/SS_2021_SEMINAR_Reinforcement_Learning_in_der_Sprachtechnologie/main/materials/images/robustness.png" alt="robustness" style="zoom:40%;" />
<br><br>

**Related Work** 
+ word replacement methods
  + outperformed by Data Boost
  + word replacement brings limited improvement 
  + flawed syntactic structure
  + low readability
+ other works mostly have higher perplexity
  + due to partial generation
  + does not take context into account
  + (Perplexity is a measurement of how well a probability distribution or probability model predicts a sample. A low perplexity indicates the probability distribution is good at predicting the sample.)
+ Data Boost outperforms all of them

<img src="https://raw.githubusercontent.com/clause-bielefeld/SS_2021_SEMINAR_Reinforcement_Learning_in_der_Sprachtechnologie/main/materials/images/related-work.png" alt="related-work" style="zoom:50%;" />
<br><br>

**Limitations**
+ to extract explicit lexical features for the metaphor, sarcastic and formal classes
  + could be because syntactic features play a role in these classes  
  + Data Boost generation is token-by-token

**Conclusion / Averages of Data Boost**:
+ Data Boost generates sentence-level augmentation
  + high readability and class consistency
  + greater variety in terms of vocabulary and sentence structure.
+ Data Boost is easy to deploy
  + no need for external datasets or training separate systems from scratch
+ Data Boost is powerful
  + brings 10% F1 improvement using 10 % true data



### Mentions / Discussion: 

+ Sometimes it is confusing which training data they used. (Original data only, original and augmented data or augmented data only)
+ Human Evaluation -  Each participant was paid 75 cents for their participation in this study
+ Curiously, for the neutral (Sentiment), abusive (Offense) and hateful (Offense) labels, both Data Boost and vanilla GPT-2 generated samples were rated as more readable the original samples.
* The code will be made available upon request 
+ They mention that there are methods that have not yet been tried for text augmentation and that they do not use reinforcement learning to have fine-grained control over the generation, which they found particularly helpful when dealing with multiple labels within the same task.

### A) Paper Presentation III: Anne

# Title: Reinforcement-Learning Based Portfolio Management with Augmented Asset Movement Prediction States 

#### Link: https://ojs.aaai.org//index.php/AAAI/article/view/5462

### Summary
- trading is a decision-making process which includes the continuous derivation of valuable information from various data sources and sequential decision optimization

- The paper introduces a state augmented reinforcement learning framework (SARL) for portfolio management (PM) to adress data heterogenity and envionment uncertainty challenges of automated PM

- SARL augments the asset information by their price movement prediction as additional states, whereby the prediction can be based exclusively on financial data (e.g. asset prices) or derived from alternative sources (such as news articles)

- two experiments on two real data sets validate the effectiveness of SARL in comparison to state of the art reinforcement learning (RL) frameworks for trading:

 (i) Bitcoin market 
 (ii) High-tech stock 

- extensive simulations are carried out to demonstrate the importance of the state enhancement, which provides new insights and significantly improves performance compared to the standard RL-based PM method and other baselines

### Problem Definition
- PM is still largely based on linear models and the Markowitz framework

   -> relies on accurate prediction of market prices and restricted assumptions such as past probability distribution of assets’    returns fully representing the future


   #### Challenges/Problems of recent RL methods for trading are:

 (1) data heterogenity 

    - due to the fact that information data, such as news articles are very unstructured
    
 (2) Environment uncertainty

    - the non-stationary nature of financial markets induces uncertainty and often causes a distribution shift between training and testing data
    

### Idea: An hierarchical approach which binds supervised learning and RL into a unified framework such that it can be trained with standard RL methods
The framework aims to leverage additional diverse information from alternative sources (other than classical structured financial data) into augmented states which then will be the used for reinforcement learning

--> The SARL framework can easily incorporate different data sources through the use of an encoder for state augmentation

#### Steps:

1. employ an end-to-end network to extract asset movement information frogm internal source (e.g. price up/down predicted label from historical prices) or external source (e.g. news embedding)

2. integrate it with the prices of assets for state augmentation

3. adopt a deterministic policy gradient algorithm based on the augmented state for learning the policy of PM


![alt text](https://d3i71xaburhd42.cloudfront.net/61bee52afa721d13982289497f3408e54444f85b/3-Figure1-1.png " ")

#### Example proceeding for external features from news articles: 

- collect financial news articles related to the assets 

- use different kinds of Natural Language Processing methods as encoders to embed the news

- feed the embedding into a hierarchical attention network (HAN) to train a binary classifier to predict the price movement

- the features in the last layer before the softmax layer are extracted to represent the embedding of the news

- integrate the embedding into the state for augmentation


### State Augmentation Framework:
#### The Augmented Asset Movement Prediction State


s* = observable state (i.e. current asset price)

encoder δ: summarizes asset movement prediction from past asset prices or news

    - the encoder δ takes different types of data sources and transforms their contents into informatve representations to be augmented to the asset prices for training an RL agent

    - example encoder: a feature extraction function derived from a text classifier, which is trained on the word embeddings of news for asset movement prediction
augmented state s: s = (s*,δ)


--> Goal: Train a recurrent neural network with long short-term memory to predict the asset movement. The binary output (price up/down) will guide the model to choose a better strategy.


### RL Framework:
** Environment: ** market consisting of all the assets for PM and other Information

** Agent: ** Algorithm which observes the environment and makes decisions to interact with the market and rebalance the portfolio

** Internal data source: ** asset prices

** External data source: ** financial news articles

** State Space: **
- augmented asset prices

** Action Space: **
- what the agent should do is to reallocate the assets into assets -> adjust the vector of total assets 

- The desired reallocating weights at a time step defines the action vector

** Reward Function: **
- defined based on profit the agent made
- accumulated product value (equivalent to maximize the sum of the logarithmic value)


### Evaluation

**Figure 3:** The portfolio value of different PM methods. SARL is our proposed state augmentation RL method, DPM is the state-of-art standard RL method in PM. CRP, OL- MAR, WMAMR are baseline financial PM methods.

<img src="https://raw.githubusercontent.com/clause-bielefeld/SS_2021_SEMINAR_Reinforcement_Learning_in_der_Sprachtechnologie/main/materials/images/portfolio_values.png" alt="Portfolio Values" style="width: 450px;"/>


--> SARL improves PV by 140.9% and 15.7% when compared to the state-of- art RL algorithm for PM (DPM)

**Table 1: ** The training and testing accuracy of the text classifier for different word embedding methods.

<img src="https://d3i71xaburhd42.cloudfront.net/61bee52afa721d13982289497f3408e54444f85b/6-Table1-1.png" alt="sparsity" style="width: 480px;"/>

--> the best training/testing accuracy is no greater than 66%/61%, which leads to suggesting noisy information in the collected news

** Figure 5:** The sparsity test on Bitcoin dataset. Each subfig- ure shows the results of SARL whose state is augmented by simulated price prediction labels with different sparsity. LD is label density from {20%, 50%, 80%, 100%}. 

<img src="https://d3i71xaburhd42.cloudfront.net/61bee52afa721d13982289497f3408e54444f85b/500px/7-Figure5-1.png" alt="sparsity" style="width: 480px;"/>


--> The performance of PM benefits from higher label density
--> The figure shows that even if there are only labels with density 50% but 70% accuracy, the portfolio value still has an improvement of 90.3% when compared to the state of the art (DPM). This suggests that if there are labels with high confidence, an improvement of the PM strategy is possible even if the labels are sparse

** Figure 6:** The comparison between states augmented by dif- ferent news embedding and randomly simulated labels.

<img src="https://d3i71xaburhd42.cloudfront.net/61bee52afa721d13982289497f3408e54444f85b/7-Figure6-1.png"  style="width: 480px;"/>

--> verifies the existence of the hidden correlation in financial news

### Results
- SARL outperforms the state-of- the-art method by 140.9% on the Bitcoin dataset and 15.7% on the HighTech dataset

- SARL is more generalizable than the former regarding data distribution shift


The experiments show that:

(1) The exploitation of diverse information can reduce the impact of environment uncertainty

 (2) High-density (more frequent) external information can help boost the overall PM performance even when the information is noisy

(3) Low-density but high-accuracy external information can also improve the PM performance


### Critical Discussion
- **++** The paper is easy to understand due to a clear structure and informative visualisation 

- **++** Sheds light onto a very interesting field wich can be expanded for example by discussion of language processing (i.e. detecting positive/negative tones in news articles) for the encoding

- **-** The used encoders are not presented in the paper

- **-** The authors don't explain how the stock movement signal takes impact on the augmented state and how high the predicted price movement is due to the encoders  

- **-** There ist no primary explanation why it may be useful to first predict the state, as it turns out to be

- **-** No information about how well the agent performed (i.e. in comparison to the real course rates) 

- **-** little extensive conclusion/interpretation and no advices for future research







### Discussion



***

## C) Practice

#### Examples III

Game: Frozen Lake

I am using the gym environment of openai today. 
You can install it this way: 

`conda install -c conda-forge gym`

The game we try to solve is the frozen lake game:
<img src="https://camo.githubusercontent.com/f558f268f3c1a45f0a88342113476f34ce894896c30b66fdc3101c8d090a0a0a/68747470733a2f2f616e616c7974696373696e6469616d61672e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031382f30332f46726f7a656e2d4c616b652e706e67" width="500"/>

For this we use the openai gym environment implementation from here: 
https://gym.openai.com/envs/FrozenLake-v0/

You can find the source code in this repository:
https://github.com/openai/gym/blob/master/gym/envs/toy_text/frozen_lake.py

The environment is an implementation of the same interface as we implemented last week. 

Let's start:

-----

In [3]:
# Check GPU reachability 
import torch
print(torch.__version__)
print(torch.cuda.is_available())

1.7.1
True


In [4]:
import numpy as np
import gym 
import random 
import time
from abc import ABC, abstractmethod
from IPython.display import clear_output

In [5]:
# get an instance of the frozen lake gym environment
env = gym.make("FrozenLake-v0")

In [6]:
# get some information from the environment
action_space = env.action_space
#print(action_space)
action_space_size = env.action_space.n
#print(action_space_size)
state_space = env.observation_space 
print(state_space)
state_space_size = env.observation_space.n
print(state_space_size)

Discrete(16)
16


In [7]:
# Q-TABLE
# build our action-value table | Q-TABLE
# as you already know, the q-table looks like this
# state | action_space

q_table = np.zeros((state_space_size, action_space_size))
#print(q_table)

In [8]:
# Training Parameters
num_episodes = 10000
max_steps_per_episode = 100
num_test_episodes = 3     

# q-learning | update parameters
learning_rate = 0.1
discount_rate = 0.99

# exploration-exploitation trade off
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [9]:
# Q-LEARNING

# collect rewards somewhere to visualize our learning curve
rewards_of_all_episodes = []

# Training Loop
for episode in range(num_episodes):
    # reset/initialize the environment first
    state = env.reset()
    # set done back to false at the beginning of an episode
    done = False
    # reset our rewards collector | return for the beginning episode
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        # select an action
        # use our exploration exploitation trade off -> do we explore or exploit in this timestep ?
        exploration_rate_threshold = random.uniform(0,1)
        if(exploration_rate_threshold > exploration_rate):
            action = np.argmax(q_table[state, : ])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        # Update Q-Table Q(s,a) using the bellman update  
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, : ]))
        
        # update the state to the new state
        state = new_state
        # collect the reward
        rewards_current_episode += reward
        
        if (done == True):
            break
    
    # after we finish an episode, make sure to update the exploration rate
    # decay the exploration rate the longer the time goes on
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    # append our rewards for this episode for learning curve
    rewards_of_all_episodes.append(rewards_current_episode)

In [10]:
# LEARNING STATISTICS 
# for each episode print the stats of the episode
rewards_per_thousand_episodes = np.split(np.array(rewards_of_all_episodes),num_episodes/1000)
count = 1000
print('*****INFO: average reward per thousand episodes: ***** \n')
for reward in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(reward/1000)))
    count += 1000
    
# print our learned q-table
print("\n\n ***** Q-TABLE ***** \n")
print(q_table)

*****INFO: average reward per thousand episodes: ***** 

1000 :  0.05100000000000004
2000 :  0.23100000000000018
3000 :  0.3930000000000003
4000 :  0.5500000000000004
5000 :  0.6230000000000004
6000 :  0.7040000000000005
7000 :  0.6530000000000005
8000 :  0.6980000000000005
9000 :  0.6740000000000005
10000 :  0.7010000000000005


 ***** Q-TABLE ***** 

[[0.6032918  0.52051926 0.52757518 0.52314479]
 [0.27564079 0.31121611 0.37842906 0.53454468]
 [0.40776611 0.42450012 0.41705814 0.47372005]
 [0.29044264 0.29152389 0.27231605 0.45458253]
 [0.62139108 0.40005343 0.42102558 0.36363938]
 [0.         0.         0.         0.        ]
 [0.41566046 0.174966   0.19631856 0.08520832]
 [0.         0.         0.         0.        ]
 [0.46381587 0.36760085 0.51062419 0.66496301]
 [0.30029783 0.73460421 0.52349917 0.43820418]
 [0.65238002 0.34436335 0.45619523 0.33578276]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.25909959 0.44331484 0.84152439

In [ ]:
# EVALUATION | TESTING | watching our agent play
for episode in range(num_test_episodes):
    state = env.reset()
    done = False
    print("INFO:*****EPISODE ", episode+1, "\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("INFO: ***** agent reached the goal. *****")
                time.sleep(3)
            else:
                print("INFO: ***** agent died.")
                time.sleep(3)
            clear_output(wait=True)
            break
        
        state = new_state

env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG


***
***
***

Game: Taxi 

Find the OpenAI Gym Environment here: https://gym.openai.com/envs/Taxi-v3/

### ENVIRONMENT

In [52]:
# DOMAIN = the data_object (JSON SERIALIZABLE)
class Environment():
    """The main Environment class. It encapsulates an environment with
    arbitrary behind-the-scenes dynamics. An environment can be
    partially or fully observed.
    The main API methods that users of this class need to know are:
        step
        reset
        render
        close
        seed
    And set the following attributes:
        action_space: The Space object corresponding to valid actions
        observation_space: The Space object corresponding to valid observations
        reward_range: A tuple corresponding to the min and max possible rewards
    Note: a default reward range set to [-inf,+inf] already exists. Set it if you want a narrower range.
    The methods are accessed publicly as "step", "reset", etc...
    """
    # Set this in SOME subclasses
    metadata = {'render.modes': []}
    reward_range = (-float('inf'), float('inf'))
    spec = None

    def __init__(self, action_space=None, observation_space=None):
        # Set variables
        self.action_space = action_space
        self.observation_space = observation_space
    
# REPOSITORY = the functionality interface
class EnvironmentRepository(ABC):
    @abstractmethod
    def step(self, action):
        """Run one timestep of the environment's dynamics. When end of
        episode is reached, you are responsible for calling `reset()`
        to reset this environment's state.
        Accepts an action and returns a tuple (observation, reward, done, info).
        Args:
            action (object): an action provided by the agent
        Returns:
            observation (object): agent's observation of the current environment
            reward (float) : amount of reward returned after previous action
            done (bool): whether the episode has ended, in which case further step() calls will return undefined results
            info (dict): contains auxiliary diagnostic information (helpful for debugging, and sometimes learning)
        """
        pass

    @abstractmethod
    def reset(self):
        """Resets the environment to an initial state and returns an initial
        observation.
        Note that this function should not reset the environment's random
        number generator(s); random variables in the environment's state should
        be sampled independently between multiple calls to `reset()`. In other
        words, each call of `reset()` should yield an environment suitable for
        a new episode, independent of previous episodes.
        Returns:
            observation (object): the initial observation.
        """
        pass

    @abstractmethod
    def render(self, mode='human'):
        """Renders the environment.
        The set of supported modes varies per environment. (And some
        environments do not support rendering at all.) By convention,
        if mode is:
        - human: render to the current display or terminal and
          return nothing. Usually for human consumption.
        - rgb_array: Return an numpy.ndarray with shape (x, y, 3),
          representing RGB values for an x-by-y pixel image, suitable
          for turning into a video.
        - ansi: Return a string (str) or StringIO.StringIO containing a
          terminal-style text representation. The text can include newlines
          and ANSI escape sequences (e.g. for colors).
        Note:
            Make sure that your class's metadata 'render.modes' key includes
              the list of supported modes. It's recommended to call super()
              in implementations to use the functionality of this method.
        Args:
            mode (str): the mode to render with
        Example:
        class MyEnv(Env):
            metadata = {'render.modes': ['human', 'rgb_array']}
            def render(self, mode='human'):
                if mode == 'rgb_array':
                    return np.array(...) # return RGB frame suitable for video
                elif mode == 'human':
                    ... # pop up a window and render
                else:
                    # just raise an exception
                    super(MyEnv, self).render(mode=mode)
        """
        pass

    @abstractmethod
    def close(self):
        """Override close in your subclass to perform any necessary cleanup.
        Environments will automatically close() themselves when
        garbage collected or when the program exits.
        """
        pass


In [53]:
# REPOSITORY IMPLEMENTATION = the way how you would like to implement it
class EnvironmentRepositoryImpl(EnvironmentRepository):
    # Initialize / Instance Attributes
    def __init__(self, environment):
        # Set variables
        self.data_object = environment
        print('Environment initialized')

    def step(self, action):
        state = self.data_object.step(action)
        return state

    def reset(self):
        state = self.data_object.reset()
        return state

    def render(self):
        self.data_object.render()

    def close(self):
        state = self.data_object.close()

    def get_action_space(self):
        # get action space from api of the playground or via js in browser using selenium
        action_space = self.data_object.action_space
        return action_space

    def get_observation_space(self):
        # get observation space of the playground from api or via js in browser using selenium
        observation_space = self.data_object.observation_space
        return observation_space

### AGENT

In [54]:
# DOMAIN
class Agent():
    # class variables
    agent_variable = ""
    # class methods
    def __init__(self, agent_variable=""):
        self.agent_variable = agent_variable
        
# REPOSITORY
class AgentRepository(ABC):
    @abstractmethod
    def get_action(self, state): # This is the agent's POLICY, if you will
        """ Agent gets a state as input and returns an action 
        """
        pass

In [77]:
# REPOSITORY IMPLEMENTATION
class AgentRepositoryImpl(AgentRepository):
    # Initializer / Instance Attributes
    def __init__(self, environment, agent):
        # Set variables
        self.data_object = agent
        self.environment = environment
        self.action_space = self.environment.action_space
        self.observation_space = self.environment.observation_space
        self.action_space_size = self.environment.action_space.n
        self.observation_space_size = self.environment.observation_space.n
        # INIT Q-TABLE
        self.q_table = np.zeros((self.observation_space_size, self.action_space_size))
        # INIT AGENT PARAMETERS
        self.learning_rate = 0.7           # Learning rate
        self.discount_rate = 0.618         # Discounting rate
        self.exploration_rate = 1.0        # Exploration rate
        self.max_exploration_rate = 1.0    # Exploration probability at start
        self.min_exploration_rate = 0.01   # Minimum exploration probability 
        self.exploration_decay_rate = 0.01 # Exponential decay rate for exploration probability
        print('Agent initialized.')

    def get_action(self, state):
        #EXPLORATION-EXPLOITATION TRADE OFF
        exploration_rate_threshold = random.uniform(0,1)
        if(exploration_rate_threshold > self.exploration_rate):
            # get action from q table
            action = np.argmax(self.q_table[state, : ])
        else:
            # get random action
            action = self.get_random_action()
        return action
    
    def get_random_action(self):
        #action_set = random.sample(self.action_space, 1)
        #action = action_set[0]
        action = self.action_space.sample()
        return action
    
    def update_q_table(self, state, action, reward, new_state):
        self.q_table[state, action] = self.q_table[state, action] * (1 - self.learning_rate) + self.learning_rate * (reward + self.discount_rate * np.max(self.q_table[new_state, : ]))
        
    def update_exploration_rate(self, episode_num):
        self.exploration_rate = self.min_exploration_rate + (self.max_exploration_rate - self.min_exploration_rate) * np.exp(-self.exploration_decay_rate*episode_num)
    
    def get_exploit_action(self, state):
        action = np.argmax(self.q_table[state, : ])
        return action

### TRAINING

In [78]:
# Training Parameters
num_episodes = 50000        # Total episodes
max_steps_per_episode = 100 # Max steps per episode
num_test_episodes = 5     # Total test episodes

In [83]:
# Setting up the Environment

# get the environment
env = gym.make("Taxi-v3")

# get some information from the environment
action_space = env.action_space
print(action_space)
action_space_size = env.action_space.n
print(action_space_size)
observation_space = env.observation_space 
print(observation_space)
observation_space_size = env.observation_space.n
print(observation_space_size)
reward_range = env.reward_range
print(reward_range)

environment_data_object = env #Environment(action_space, observation_space)
environment = EnvironmentRepositoryImpl(environment_data_object)

# Setting up the Agent
agent_data_object = Agent()
agent = AgentRepositoryImpl(environment_data_object, agent_data_object)

Discrete(6)
6
Discrete(500)
500
(-inf, inf)
Environment initialized
Agent initialized.


In [80]:
# TRAINING
# collect rewards somewhere to visualize our learning curve
rewards_of_all_episodes = []

# Training Loop
for episode in range(num_episodes):
    # reset/initialize the environment first
    state = environment.reset()
    # set done back to false at the beginning of an episode
    done = False
    # reset our rewards collector | return for the beginning episode
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        # select an action
        # use our exploration exploitation trade off -> do we explore or exploit in this timestep ?
        action = agent.get_action(state)
            
        new_state, reward, done, info = environment.step(action)
        
        # Update Q-Table Q(s,a) using the bellman update  
        agent.update_q_table(state, action, reward, new_state)
        
        # update the state to the new state
        state = new_state
        # collect the reward
        rewards_current_episode += reward
        
        if (done == True):
            break
    
    # after we finish an episode, make sure to update the exploration rate
    # decay the exploration rate the longer the time goes on
    agent.update_exploration_rate(episode)
    # append our rewards for this episode for learning curve
    rewards_of_all_episodes.append(rewards_current_episode)

In [81]:
# LEARNING STATISTICS 
# for each episode print the stats of the episode
rewards_per_thousand_episodes = np.split(np.array(rewards_of_all_episodes),num_episodes/1000)
count = 1000
print('*****INFO: average reward per thousand episodes: ***** \n')
for reward in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(reward/1000)))
    count += 1000
    
# print our learned q-table
print("\n\n ***** Q-TABLE ***** \n")
print(agent.q_table)

*****INFO: average reward per thousand episodes: ***** 

1000 :  -45.3959999999998
2000 :  7.407999999999966
3000 :  7.5049999999999635
4000 :  7.351999999999967
5000 :  7.470999999999966
6000 :  7.561999999999962
7000 :  7.5269999999999735
8000 :  7.457999999999962
9000 :  7.48799999999996
10000 :  7.464999999999965
11000 :  7.399999999999965
12000 :  7.312999999999967
13000 :  7.3119999999999585
14000 :  7.335999999999961
15000 :  7.421999999999961
16000 :  7.3349999999999556
17000 :  7.301999999999971
18000 :  7.198999999999964
19000 :  7.298999999999972
20000 :  7.408999999999964
21000 :  7.5029999999999575
22000 :  7.471999999999971
23000 :  7.283999999999966
24000 :  7.396999999999963
25000 :  7.408999999999962
26000 :  7.49899999999996
27000 :  7.361999999999972
28000 :  7.333999999999961
29000 :  7.434999999999964
30000 :  7.4679999999999644
31000 :  7.595999999999968
32000 :  7.188999999999968
33000 :  7.5039999999999605
34000 :  7.349999999999961
35000 :  7.42599999999996
360

In [85]:
# EVALUATION | TESTING | watching our agent play
for episode in range(num_test_episodes):
    state = environment.reset()
    done = False
    print("INFO:*****EPISODE ", episode+1, "\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        environment.render()
        time.sleep(0.3)
        
        action = agent.get_exploit_action(state)
        new_state, reward, done, info = environment.step(action)
        
        if done:
            clear_output(wait=True)
            environment.render()
            if reward == 20:
                print("INFO: ***** agent reached the goal. *****")
                time.sleep(3)
            else:
                print("INFO: ***** agent missed the goal.")
                time.sleep(3)
            clear_output(wait=True)
            break
        
        state = new_state

environment.close()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)


In [20]:
# LITTLE HOMEWORK
# 1. get an environment of the openai gym (e.g. cart pole, lunar lander, breakout)
# 2. print the essential information about the environment (state space, action space, ...)
# 3. write an agent class
# 4. train your agent on the environment using Q-Learning (play around with the hyperparameters for your environment)
# 5. Plot your results (average reward, q-table)

***

# TODO's

1. Send your finished presentations (+ possibly annotated paper) by **Monday 12.00 AM/midnight** via email to henrik.voigt@uni-jena.de

2. Send your little HOMEWORK to henrik.voigt@uni-jena.de by using the naming convention: HOMEWORK_02_FIRSTNAME_LASTNAME.ipynb until **June 9th 12.00 AM/midnight**

***
